# Site settings
title: "burnning's coding life"
description: > # this means to ignore newlines until "baseurl:"
  burning's coding life

author:
  name: burning
  email: markaii0791@gmail.com
  link: http://burningsun.xyz

markdown: kramdown
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://burningsun.xyz" # the base hostname & protocol for your site

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

sass:
  style: compressed

# Plugins
gems:
  - jekyll-sitemap


# 第三方插件
# Social account
twitter:  markaii0791
# weibo:    ID
github:   markaii

# Comment
disqus_shortname: burning

# Google Analytics
google_analytics: UA-66029258-1


